# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0886210c78cf9b8edeb423f5445f2a6c4fb8e249fec7ab4d4f5365056426f270b06b6b6c6d0c2cdf732ef0fd522514cb5af46c3fd5a844d6a159c41110e3a96d

test:
  secret_key_base: 49772a2c2b488cecbd349636932f52113345ef227ce52d19370743915a8ed1dc5a4c2112d9cf30a0678eaa07107e66cfe62b91d2fcf5da6616ad0257e6ff4b79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
