# == Schema Information
#
# Table name: category_reports
#
#  id          :integer          not null, primary key
#  category_id :integer
#  text        :text
#  created_at  :datetime
#  updated_at  :datetime
#  value_min   :integer
#  value_max   :integer
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CategoryReportsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CategoryReport. As you add validations to CategoryReport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CategoryReportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all category_reports as @category_reports" do
      category_report = CategoryReport.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:category_reports)).to eq([category_report])
    end
  end

  describe "GET #show" do
    it "assigns the requested category_report as @category_report" do
      category_report = CategoryReport.create! valid_attributes
      get :show, {:id => category_report.to_param}, valid_session
      expect(assigns(:category_report)).to eq(category_report)
    end
  end

  describe "GET #new" do
    it "assigns a new category_report as @category_report" do
      get :new, {}, valid_session
      expect(assigns(:category_report)).to be_a_new(CategoryReport)
    end
  end

  describe "GET #edit" do
    it "assigns the requested category_report as @category_report" do
      category_report = CategoryReport.create! valid_attributes
      get :edit, {:id => category_report.to_param}, valid_session
      expect(assigns(:category_report)).to eq(category_report)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CategoryReport" do
        expect {
          post :create, {:category_report => valid_attributes}, valid_session
        }.to change(CategoryReport, :count).by(1)
      end

      it "assigns a newly created category_report as @category_report" do
        post :create, {:category_report => valid_attributes}, valid_session
        expect(assigns(:category_report)).to be_a(CategoryReport)
        expect(assigns(:category_report)).to be_persisted
      end

      it "redirects to the created category_report" do
        post :create, {:category_report => valid_attributes}, valid_session
        expect(response).to redirect_to(CategoryReport.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved category_report as @category_report" do
        post :create, {:category_report => invalid_attributes}, valid_session
        expect(assigns(:category_report)).to be_a_new(CategoryReport)
      end

      it "re-renders the 'new' template" do
        post :create, {:category_report => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested category_report" do
        category_report = CategoryReport.create! valid_attributes
        put :update, {:id => category_report.to_param, :category_report => new_attributes}, valid_session
        category_report.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested category_report as @category_report" do
        category_report = CategoryReport.create! valid_attributes
        put :update, {:id => category_report.to_param, :category_report => valid_attributes}, valid_session
        expect(assigns(:category_report)).to eq(category_report)
      end

      it "redirects to the category_report" do
        category_report = CategoryReport.create! valid_attributes
        put :update, {:id => category_report.to_param, :category_report => valid_attributes}, valid_session
        expect(response).to redirect_to(category_report)
      end
    end

    context "with invalid params" do
      it "assigns the category_report as @category_report" do
        category_report = CategoryReport.create! valid_attributes
        put :update, {:id => category_report.to_param, :category_report => invalid_attributes}, valid_session
        expect(assigns(:category_report)).to eq(category_report)
      end

      it "re-renders the 'edit' template" do
        category_report = CategoryReport.create! valid_attributes
        put :update, {:id => category_report.to_param, :category_report => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested category_report" do
      category_report = CategoryReport.create! valid_attributes
      expect {
        delete :destroy, {:id => category_report.to_param}, valid_session
      }.to change(CategoryReport, :count).by(-1)
    end

    it "redirects to the category_reports list" do
      category_report = CategoryReport.create! valid_attributes
      delete :destroy, {:id => category_report.to_param}, valid_session
      expect(response).to redirect_to(category_reports_url)
    end
  end

end
